title: Alejandro Escalante
description: una pagina personal
show_downloads: true
other:
  home: https://alex-esc.github.io/light/
  docs: https://alex-esc.github.io/light/docs/document_index.html
  about: https://alex-esc.github.io/light/pages/about.html
